# Copyright (c) 2013 to Jason van Zyl
# All rights reserved. This program and the accompanying materials                                                                                                                                          
# are made available under the terms of the Eclipse Public License v1.0                                                                                                                                     
# which accompanies this distribution, and is available at                                                                                                                                                  
# http://www.eclipse.org/legal/epl-v10.html   
#
# This generates everything needed to create a distributions
#
# https://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/tree/packages/org.eclipse.epp.package.rcp.feature/feature.xml

productId: io.tesla.ide.rcp.product

repos: 
 - 
   id: eclipse
   url: http://download.eclipse.org/releases/luna 

platforms:
 - osx

featureSets: 
 -
  eclipse:
   features:
    - id: org.eclipse.platform
    - id: org.eclipse.platform.source
    - id: org.eclipse.rcp
    - id: org.eclipse.rcp.source
    - id: org.eclipse.jdt
    - id: org.eclipse.jdt.source
    - id: org.eclipse.pde
    - id: org.eclipse.pde.source
    - id: org.eclipse.equinox.p2.user.ui
    - id: org.eclipse.help
    - id: org.eclipse.egit
    - id: org.eclipse.jgit
    - id: org.eclipse.wb.core.feature
    - id: org.eclipse.wb.core.ui.feature
    - id: org.eclipse.wb.layout.group.feature
    - id: org.eclipse.wb.swt.feature
    - id: org.eclipse.wb.rcp.feature   
    - id: org.eclipse.mylyn.github.feature     
 -  
  m2eclipse:
   features:
    - id: io.tesla.ide.feature
    - id: org.eclipse.m2e.feature
    - id: org.eclipse.m2e.logback.feature
 -    
  m2e:
   repo: http://nexus.tesla.io:8081/nexus/content/sites/m2e.extras/m2e/1.5.0/N/LATEST/
   features:  
    - id: org.sonatype.tycho.m2e.feature    
 -    
  m2eTycho:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-tycho/0.7.0/N/0.7.0.201302171659
   features:  
    - id: org.sonatype.tycho.m2e.feature
 -    
  sourcelookup:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/sourcelookup/1.1.0/N/1.1.0.201311250413/
   features:  
    - id: com.ifedorenko.m2e.sourcelookup.feature
 -    
  tychodev:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/mavendev/0.2.0/N/0.2.0.201311250430/
   features:  
    - id: com.ifedorenko.m2e.mavendev.feature
 -    
  plexus:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-plexus/0.15.0/N/0.15.0.201302101151
   features:  
    - id: org.sonatype.m2e.plexus.annotations.feature
 -    
  modello:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-modello/0.16.0/N/0.16.0.201302171621
   features:  
    - id: org.sonatype.m2e.modello.feature
 -    
  sisu:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-sisu/0.15.0/N/0.15.0.201207090126/
   features:  
    - id: org.sonatype.m2e.sisu.feature
 -    
  mavenarchiver:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.15.0/N/0.15.0.201212080009/
   features:  
    - id: org.sonatype.m2e.mavenarchiver.feature
 -    
  m2eEgit:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-egit/0.14.0/N/0.14.0.201401060018/
   features:  
    - id: org.sonatype.m2e.egit.feature
 -    
  m2eAntlr:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-antlr/0.15.0/N/0.15.0.201302040035/
   features:  
    - id: org.sonatype.m2e.antlr.feature
 -    
  nexuside:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/nexuside/1.0.0/N/1.0.0.201303100224/
   features:  
    - id: com.ifedorenko.m2e.nexusdev.feature
 -    
  onboarding:
   repo: http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-onboarding/0.0.1/N/0.0.1.201311162311/
   features:  
    - id: io.tesla.m2e.onboarding.feature
 -    
  yedit:
   repo: http://dadacoalition.org/yedit/
   features:  
    - id: org.dadacoalition.yedit
 -    
  xtend2:
   repo: http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases
   features:  
    - id: org.eclipse.xtext.xtend2.sdk
 -    
  eclipsecolor:
   repo: http://eclipse-color-theme.github.com/update
   features:  
    - id: com.github.eclipsecolortheme.feature
 -    
  chrometheme:
   repo: https://raw.github.com/jeeeyul/eclipse-themes/master/net.jeeeyul.eclipse.themes.updatesite
   features:  
    - id: net.jeeeyul.eclipse.themes.feature
 -    
  cssspy: 
   repo: http://download.eclipse.org/e4/downloads/drops/S-0.15-201401152200/repository/
   features:  
    - id: org.eclipse.e4.tools.css.spy.feature
